# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_last_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_mac', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('auto_off', models.PositiveIntegerField(default=1)),
                ('dur_on', models.FloatField(default=0.2)),
                ('dur_off', models.FloatField(default=0.2)),
                ('post_interval', models.FloatField(default=3)),
                ('points_for_scan', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended', models.BooleanField(default=False)),
                ('points_goal', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('time_last_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Client')),
                ('gameroud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameRound')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
    ]
