# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_id', models.PositiveIntegerField(unique=True)),
                ('light_on', models.PositiveIntegerField(default=0)),
                ('auto_off', models.BooleanField(default=True)),
            ],
        ),
    ]
