# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_clients_auto_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='auto_on',
        ),
    ]
