# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170920_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameround',
            options={'ordering': ['time_created']},
        ),
        migrations.AddField(
            model_name='score',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
