# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_clients_auto_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.TextField(unique=True),
        ),
    ]
