# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170920_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
