# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170919_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
