# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170920_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
