# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170920_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='gameroud',
            new_name='gameround',
        ),
    ]
