# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170919_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='client_id',
            new_name='client_mac',
        ),
    ]
