# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170919_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='light_on',
        ),
        migrations.AddField(
            model_name='clients',
            name='dur_off',
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name='clients',
            name='dur_on',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='clients',
            name='auto_off',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
