# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170919_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='post_interval',
            field=models.FloatField(default=3),
        ),
    ]
